import React, { useState, useRef } from 'react';
import {
  Modal, ModalHeader, ModalBody, ModalFooter,
  Form, FormGroup, TextInput, TextArea, Button, Label, Flex, FlexItem,
} from '@patternfly/react-core';
import { TrashIcon } from '@patternfly/react-icons';

const TYPE_META = {
  'external-url': { label: 'External URL', urlPlaceholder: 'https://example.com', urlLabel: 'URL' },
  'lab':          { label: 'Hands-on Lab', urlPlaceholder: 'https://zero.rhdp.net/lab/your-lab-slug.prod', urlLabel: 'Lab URL' },
  'arcade':       { label: 'Arcade Demo',  urlPlaceholder: 'https://interact.redhat.com/share/YOUR_FLOW_ID', urlLabel: 'Share URL' },
  'video-loop':   { label: 'Video Loop (ambient reel)' },
};

function slugify(v) {
  return v.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 64);
}

function emptyCard(type) {
  const base = { id: '', title: '', summary: '', enabled: true, _isNew: true };
  if (type === 'external-url' || type === 'lab') {
    base.demo = { type, url: '', long_description: '' };
    if (type === 'lab') base.demo.duration = '';
  } else if (type === 'arcade') {
    base.demo = { type, share_url: '', title: '', aspect_ratio: '' };
  } else if (type === 'video-loop') {
    base.demo = { type, _mediaFile: null, _videoFiles: [] };
  }
  return base;
}

function VideoLoopFields({ demo, onChange }) {
  const inputRef = useRef(null);
  const files = demo._videoFiles || [];
  return (
    <FormGroup label="Video files" isRequired>
      <div style={{ marginBottom: 8 }}>
        {files.length === 0 && (
          <span style={{ color: '#6a6e73', fontSize: '0.875rem' }}>No videos added yet</span>
        )}
        {files.map((f, i) => (
          <Flex key={i} alignItems={{ default: 'alignItemsCenter' }} style={{ marginBottom: 4 }}>
            <FlexItem><Label color="blue" isCompact>{f.name}</Label></FlexItem>
            <FlexItem>
              <Button variant="plain" aria-label="Remove" onClick={() =>
                onChange({ ...demo, _videoFiles: files.filter((_, j) => j !== i) })}>
                <TrashIcon />
              </Button>
            </FlexItem>
          </Flex>
        ))}
      </div>
      <Button variant="secondary" onClick={() => inputRef.current.click()}>Add video</Button>
      <input ref={inputRef} type="file" accept=".mp4,.webm" style={{ display: 'none' }}
        onChange={e => {
          const f = e.target.files[0];
          if (f) onChange({ ...demo, _videoFiles: [...files, f] });
          e.target.value = '';
        }} />
      <div style={{ fontSize: '0.8rem', color: '#6a6e73', marginTop: 4 }}>
        Videos play sequentially in a loop. Drag cards to set playback order.
      </div>
    </FormGroup>
  );
}

export default function UrlCardModal({ type, card: initialCard, onSave, onCancel }) {
  const [card, setCard] = useState(initialCard || emptyCard(type));
  const isNew = !initialCard;
  const meta = TYPE_META[type] || {};

  function setField(key, val) { setCard(p => ({ ...p, [key]: val })); }
  function setDemo(key, val) { setCard(p => ({ ...p, demo: { ...p.demo, [key]: val } })); }

  const urlLabel = meta.urlLabel || 'URL';
  const urlKey = type === 'arcade' ? 'share_url' : 'url';

  return (
    <Modal variant="medium" isOpen onClose={onCancel}>
      <ModalHeader title={`${isNew ? 'Add' : 'Edit'} ${meta.label}`} />
      <ModalBody>
        <Form>
          <FormGroup label="Card ID" isRequired
            helperText="Unique identifier — lowercase, hyphens (auto-filled from title)">
            <TextInput value={card.id}
              onChange={(_e, v) => setField('id', slugify(v))}
              placeholder="my-card-id" />
          </FormGroup>
          <FormGroup label="Title" isRequired>
            <TextInput value={card.title}
              onChange={(_e, v) => {
                setField('title', v);
                if (!card.id || card._idWasAutoGenerated) {
                  setCard(p => ({ ...p, title: v, id: slugify(v), _idWasAutoGenerated: true }));
                }
              }}
              placeholder="Card title shown on the kiosk" />
          </FormGroup>
          <FormGroup label="Summary" isRequired helperText="One sentence shown under the title">
            <TextArea value={card.summary} onChange={(_e, v) => setField('summary', v)}
              rows={2} placeholder="Brief description." />
          </FormGroup>

          {type === 'video-loop' ? (
            <VideoLoopFields demo={card.demo} onChange={d => setCard(p => ({ ...p, demo: d }))} />
          ) : (
            <>
              <FormGroup label={urlLabel} isRequired>
                <TextInput type="url" value={card.demo[urlKey] || ''}
                  onChange={(_e, v) => setDemo(urlKey, v)}
                  placeholder={meta.urlPlaceholder} />
                {type === 'arcade' && (
                  <div style={{ fontSize: '0.8rem', color: '#6a6e73', marginTop: 4 }}>
                    From Arcade: Share → copy the interact.redhat.com link
                  </div>
                )}
              </FormGroup>
              {(type === 'external-url' || type === 'lab') && (
                <FormGroup label="Description" isRequired>
                  <TextArea value={card.demo.long_description || ''}
                    onChange={(_e, v) => setDemo('long_description', v)} rows={5}
                    placeholder="Supports **bold**, [links](url), and - bullet lists." />
                </FormGroup>
              )}
              {type === 'lab' && (
                <FormGroup label="Estimated duration (optional)">
                  <TextInput value={card.demo.duration || ''}
                    onChange={(_e, v) => setDemo('duration', v)} placeholder="e.g. 30 minutes" />
                </FormGroup>
              )}
              {type === 'arcade' && (
                <>
                  <FormGroup label="Title override (optional)">
                    <TextInput value={card.demo.title || ''}
                      onChange={(_e, v) => setDemo('title', v)}
                      placeholder="Auto-fetched from Arcade if blank" />
                  </FormGroup>
                  <FormGroup label="Aspect ratio override (optional)">
                    <TextInput value={card.demo.aspect_ratio || ''}
                      onChange={(_e, v) => setDemo('aspect_ratio', v)}
                      placeholder="e.g. 56.25%" />
                  </FormGroup>
                </>
              )}
            </>
          )}
        </Form>
      </ModalBody>
      <ModalFooter>
        <Button variant="primary" onClick={() => onSave(card)}>Save</Button>
        <Button variant="link" onClick={onCancel}>Cancel</Button>
      </ModalFooter>
    </Modal>
  );
}
